run=1
[ -z "$1" ] && run="" #adapter
[ -z "$2" ] && run="" #system
[ -z "$3" ] && run="" #size_mb
[ -z "$4" ] && run="" #triple_boot
[ -z "$5" ] && run="" #clean_build
[ -z "$6" ] && run="" #Proc number
[ -z "$7" ] && run="" #Savestates
[ -z "$8" ] && run="" #Language
[ -z "$9" ] && run="" #Coverflows
[ -z "$10" ] && run="" #Screenshots
[ -z "$11" ] && run="" #Cheats
[ -z "$12" ] && run="" #Share Hibernate savestate
[ -z "$13" ] && run="" #Splash screen
[ -z "$14" ] && run="" #Nofrendo emulator use
[ -z "$15" ] && run="" #Old gameboy emulator use
[ -z "$16" ] && run="" #Single font use
[ -z "$17" ] && run="" #Filesystem size in %
[ -z "$18" ] && run="" #Force Pyocd
[ -z "$19" ] && run="" #Gnwmanager path

if [ ! -z "$run" ]; then
	size=$3
	fs_size=$(((($size*1024*1024)*${17})/100))
	if [ $5 -ge 1 ]; then make clean; fi
	if [ $4 -ge 3 ]; then
		if [ $size -eq 4 ]; then #triple boot 4MB
			echo make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE=1622016 EXTFLASH_OFFSET=2572288  FILESYSTEM_SIZE=$fs_size ADAPTER=$1 BIG_BANK=0 flash
			make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE=1622016 EXTFLASH_OFFSET=2572288 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 BIG_BANK=0 flash
		else 
			if [ "$2" == "zelda" ]; then
				((size=size-6))
				((fs_size=$((((size*${17})/100)*1024*1024))))
				echo make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=6291456 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 BIG_BANK=0 flash
				make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=6291456 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 BIG_BANK=0 flash
			else
				((size=size-3))
				((fs_size=$((((size*${17})/100)*1024*1024))))
				echo make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=3145728 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 BIG_BANK=0 flash
				make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=3145728 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 BIG_BANK=0 flash
			fi
		fi
	elif [ $4 -eq 1 ]; then
		if [ $size -eq 4 ]; then #dual boot with CFW 4MB
			echo make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE=3325952 EXTFLASH_OFFSET=868352 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
			make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE=3325952 EXTFLASH_OFFSET=868352 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
		else 
			if [ "$2" == "zelda" ]; then
				((size=size-4))
				((fs_size=$(((($size * ${17}) / 100) * 1024 * 1024))))
				echo make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=4194304 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
				make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=4194304 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
			else	
				((size=size-1))
				((fs_size=$((((size*${17})/100)*1024*1024))))
				echo make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=1048576 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
				make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=1048576 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
			fi
		fi
	elif [ $4 -eq 2 ]; then
		if [ $size -eq 4 ]; then #dual boot in bank 1 and Zelda3 in bank 2 4MB
			echo make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=1 EXTFLASH_SIZE_MB=2 EXTFLASH_OFFSET=2097152 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
			make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=1 EXTFLASH_SIZE_MB=2 EXTFLASH_OFFSET=2097152 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
		else 
			((size=size-2))
			((fs_size=$((((size*${17})/100)*1024*1024))))
			echo make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=1 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=2097152 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
			make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" GNW_TARGET=$2 INTFLASH_BANK=1 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=2097152 FILESYSTEM_SIZE=$fs_size ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
		fi
	else # single boot
	echo make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" EXTFLASH_SIZE_MB=$size FILESYSTEM_SIZE=$fs_size GNW_TARGET=$2 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=$10 CHEAT_CODES=$11 SHARED_HIBERNATE_SAVESTATE=$12 DISABLE_SPLASH_SCREEN=$13 FORCE_NOFRENDO=$14 FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
	make -j$6 FORCE_PYOCD=${18} GNWMANAGER_PATH="${19}" EXTFLASH_SIZE_MB=$size FILESYSTEM_SIZE=$fs_size GNW_TARGET=$2 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} FORCE_GNUBOY=${15} SINGLE_FONT=${16} flash
	fi
else
	echo "missing parameters. Run with ./build.sh [pico|stlink] [mario|zelda] [4 ... 512] [0|1]"
fi