run=1
[ -z "$1" ] && run="" #adapter
[ -z "$2" ] && run="" #system
[ -z "$3" ] && run="" #size_mb
[ -z "$4" ] && run="" #triple_boot
[ -z "$5" ] && run="" #clean_build
[ -z "$6" ] && run="" #Proc number
[ -z "$7" ] && run="" #Savestates
[ -z "$8" ] && run="" #Language
[ -z "$9" ] && run="" #Coverflows
[ -z "$10" ] && run="" #Screenshots
[ -z "$11" ] && run="" #Cheats
[ -z "$12" ] && run="" #Share Hibernate savestate
[ -z "$13" ] && run="" #Splash screen
[ -z "$14" ] && run="" #Nofrendo emulator use

if [ ! -z "$run" ]; then
	size=$3 
	if [ $5 -ge 1 ]; then make clean; fi
	if [ $4 -ge 3 ]; then
		if [ $size -eq 4 ]; then #triple boot 4MB
			echo make -j$6 GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE=1622016 EXTFLASH_OFFSET=2572288  ADAPTER=$1 BIG_BANK=0 flash
			make -j$6 GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE=1622016 EXTFLASH_OFFSET=2572288  ADAPTER=$1 BIG_BANK=0 flash
		else 
			((size=size-6))
			echo make -j$6 GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=6291456  ADAPTER=$1 BIG_BANK=0 flash
			make -j$6 GNW_TARGET=$2 INTFLASH_ADDRESS=0x08020000 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=6291456  ADAPTER=$1 BIG_BANK=0 flash_extflash
		fi
	elif [ $4 -eq 1 ]; then
		if [ $size -eq 4 ]; then #dual boot with CFW 4MB
			echo make -j$6 GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE=3325952 EXTFLASH_OFFSET=868352 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} flash
			make -j$6 GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE=3325952 EXTFLASH_OFFSET=868352 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} flash
		else 
			((size=size-4))
			echo make -j$6 GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=4194304 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} flash
			make -j$6 GNW_TARGET=$2 INTFLASH_BANK=2 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=4194304 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} flash
		fi
	elif [ $4 -eq 2 ]; then
		if [ $size -eq 4 ]; then #dual boot in bank 1 4MB
			echo make -j$6 GNW_TARGET=$2 INTFLASH_BANK=1 EXTFLASH_SIZE_MB=2 EXTFLASH_OFFSET=2097152 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} flash
			make -j$6 GNW_TARGET=$2 INTFLASH_BANK=1 EXTFLASH_SIZE_MB=2 EXTFLASH_OFFSET=2097152 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} flash
		else 
			((size=size-2))
			echo make -j$6 GNW_TARGET=$2 INTFLASH_BANK=1 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=2097152 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} flash
			make -j$6 GNW_TARGET=$2 INTFLASH_BANK=1 EXTFLASH_SIZE_MB=$size EXTFLASH_OFFSET=2097152 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} flash
		fi
	else # single boot
	echo make -j$6 EXTFLASH_SIZE_MB=$size GNW_TARGET=$2 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=$10 CHEAT_CODES=$11 SHARED_HIBERNATE_SAVESTATE=$12 DISABLE_SPLASH_SCREEN=$13 FORCE_NOFRENDO=$14 flash
	make -j$6 EXTFLASH_SIZE_MB=$size GNW_TARGET=$2 ADAPTER=$1 STATE_SAVING=$7 CODEPAGE=$8 UICODEPAGE=$8 COVERFLOW=$9 ENABLE_SCREENSHOT=${10} CHEAT_CODES=${11} SHARED_HIBERNATE_SAVESTATE=${12} DISABLE_SPLASH_SCREEN=${13} FORCE_NOFRENDO=${14} flash
	fi
else
	echo "missing parameters. Run with ./build.sh [pico|stlink] [mario|zelda] [4 ... 512] [0|1]"
fi